const productCategories = [
  {
    name: "Smartphones",
    description: "Mobile devices with advanced features.",
    active: true,
  },
  {
    name: "Laptops",
    description: "Portable computers for work and entertainment.",
    active: true,
  },
  {
    name: "Gaming Consoles",
    description: "Devices for playing video games.",
    active: true,
  },
  {
    name: "TVs",
    description: "Televisions for immersive entertainment.",
    active: true,
  },
  {
    name: "Cameras",
    description: "Devices for capturing photos and videos.",
    active: true,
  },
  {
    name: "Headphones",
    description: "Audio devices for personal listening.",
    active: true,
  },
  {
    name: "Drones",
    description: "Remote-controlled flying devices.",
    active: true,
  },
  {
    name: "Tablets",
    description: "Portable touchscreen devices.",
    active: true,
  },
  {
    name: "Speakers",
    description: "Audio devices for listening to music.",
    active: true,
  },
  {
    name: "Smart Home",
    description: "Devices for automating your home.",
    active: true,
  },
  {
    name: "Wearable Tech",
    description: "Technological devices worn on the body.",
    active: true,
  },
  {
    name: "Home Appliances",
    description: "Electronic devices for household tasks.",
    active: true,
  },
  {
    name: "Fitness Trackers",
    description: "Devices for monitoring health and fitness.",
    active: true,
  },
];

const productCategoriesReadyToCreate = [
  [1, "Smartphones", "Mobile devices with advanced features.", 1],
  [2, "Laptops", "Portable computers for work and entertainment.", 1],
  [3, "Gaming Consoles", "Devices for playing video games.", 1],
  [4, "TVs", "Televisions for immersive entertainment.", 1],
  [5, "Cameras", "Devices for capturing photos and videos.", 1],
  [6, "Headphones", "Audio devices for personal listening.", 1],
  [7, "Drones", "Remote-controlled flying devices.", 1],
  [8, "Tablets", "Portable touchscreen devices.", 1],
  [9, "Speakers", "Audio devices for listening to music.", 1],
  [10, "Smart Home", "Devices for automating your home.", 1],
  [11, "Wearable Tech", "Technological devices worn on the body.", 1],
  [12, "Home Appliances", "Electronic devices for household tasks.", 1],
  [13, "Fitness Trackers", "Devices for monitoring health and fitness.", 1],
];

const productsReadyToCreate = [
  [
    "iPhone 13 Pro",
    "The latest flagship smartphone from Apple.",
    1099.99,
    50,
    1,
    "Space Gray",
  ],
  [
    "Samsung Galaxy S21 Ultra",
    "Premium Android phone with top-of-the-line features.",
    1199.99,
    100,
    1,
    "Phantom Black",
  ],
  [
    "Sony PlayStation 5",
    "Next-generation gaming console with stunning graphics.",
    499.99,
    75,
    3,
    "Jet Black",
  ],
  [
    "Microsoft Xbox Series X",
    "Powerful gaming console with backward compatibility.",
    499.99,
    60,
    3,
    "Robot White",
  ],
  [
    "Samsung QLED 4K TV",
    "High-quality smart TV with vibrant colors and impressive resolution.",
    1299.99,
    40,
    4,
    "Titan Gray",
  ],
  [
    "Apple MacBook Air",
    "Lightweight and powerful laptop for everyday use.",
    999.99,
    80,
    2,
    "Silver",
  ],
  [
    "Canon EOS R5",
    "Professional mirrorless camera with exceptional image quality.",
    3799.99,
    20,
    5,
    "Black",
  ],
  [
    "Sony WH-1000XM4",
    "Premium noise-canceling headphones with immersive sound.",
    349.99,
    100,
    6,
    "Silver",
  ],
  [
    "DJI Mavic Air 2",
    "Compact and powerful drone for capturing stunning aerial footage.",
    799.99,
    30,
    7,
    "Arctic White",
  ],
  [
    "Bose QuietComfort 35 II",
    "Wireless headphones with excellent noise cancellation.",
    299.99,
    150,
    6,
    "Black",
  ],
  [
    "Nintendo Switch",
    "Versatile gaming console for both handheld and TV gaming.",
    299.99,
    90,
    3,
    "Neon Red/Neon Blue",
  ],
  [
    "Samsung Galaxy Watch 4",
    "Smartwatch with advanced health and fitness tracking features.",
    299.99,
    50,
    8,
    "Phantom Black",
  ],
  [
    "LG OLED 4K TV",
    "Premium OLED TV with deep blacks and rich colors.",
    1999.99,
    30,
    4,
    "Ceramic Black",
  ],
  [
    "Fitbit Charge 4",
    "Fitness tracker with built-in GPS and heart rate monitoring.",
    149.99,
    200,
    9,
    "Black",
  ],
  [
    "Bose SoundLink Revolve+",
    "Portable Bluetooth speaker with 360-degree sound.",
    299.99,
    80,
    10,
    "Lux Gray",
  ],
  [
    "Google Nest Hub",
    "Smart display with voice control for managing your smart home.",
    99.99,
    120,
    11,
    "Chalk",
  ],
  [
    "Microsoft Surface Pro 7",
    "Versatile 2-in-1 laptop and tablet for productivity.",
    1299.99,
    70,
    2,
    "Platinum",
  ],
  [
    "GoPro HERO9 Black",
    "Action camera with 5K video recording and advanced stabilization.",
    449.99,
    50,
    5,
    "Black",
  ],
  [
    "Amazon Echo Dot",
    "Smart speaker with Alexa voice assistant for hands-free control.",
    49.99,
    250,
    11,
    "Charcoal",
  ],
];

export {
  productCategories,
  productCategoriesReadyToCreate,
  productsReadyToCreate,
};
